<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_58fc2e6e50ad3',
  'title' => 'Background',
  'fields' => array (
    array (
      'key' => 'field_58fc2fa137f49',
      'label' => 'Color',
      'name' => 'background_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
    ),
    array (
      'key' => 'field_58fc370e5dca2',
      'label' => 'Image',
      'name' => 'background_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58fcde7b7678b',
      'label' => 'Position',
      'name' => 'background_position',
      'type' => 'select',
      'instructions' => '<a href="https://www.w3schools.com/cssref/pr_background-position.asp" target="_blank">How to use the position property</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'select' => 'select',
        'left top' => 'left top',
        'left center' => 'left center',
        'left bottom' => 'left bottom',
        'right top' => 'right top',
        'right center' => 'right center',
        'right bottom' => 'right bottom',
        'center top' => 'center top',
        'center center' => 'center center',
        'center bottom' => 'center bottom',
      ),
      'default_value' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'return_format' => 'value',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58fcdfd68f101',
      'label' => 'Repeat',
      'name' => 'background_repeat',
      'type' => 'select',
      'instructions' => '<a href="https://www.w3schools.com/cssref/pr_background-repeat.asp" target="_blank">How to use the repeat property</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'select' => 'select',
        'no-repeat' => 'no-repeat',
        'repeat' => 'repeat',
        'repeat-x' => 'repeat-x',
        'repeat-y' => 'repeat-y',
      ),
      'default_value' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'return_format' => 'value',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58fce01d15e8a',
      'label' => 'Size',
      'name' => 'background_size',
      'type' => 'select',
      'instructions' => '<a href="https://www.w3schools.com/cssref/css3_pr_background-size.asp" target="_blank">How to use the size property</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'select' => 'select',
        'auto' => 'auto',
        'cover' => 'cover',
        'contain' => 'contain',
        'flex' => 'flex',
      ),
      'default_value' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'return_format' => 'value',
      'placeholder' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'better-custom-login',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_58fce91cf22eb',
  'title' => 'Logo',
  'fields' => array (
    array (
      'key' => 'field_58fce91d03578',
      'label' => 'Image',
      'name' => 'logo_image',
      'type' => 'image',
      'instructions' => 'A max width of 320 is suggested (the default form width). You can modify with width and height settings below.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58fd6ba7ffbf9',
      'label' => 'Background Size',
      'name' => 'logo_background_size',
      'type' => 'number',
      'instructions' => 'This property is used to define the width of the logo. All non-integers will be removed.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array (
      'key' => 'field_58fce9762adb4',
      'label' => 'Height',
      'name' => 'logo_height',
      'type' => 'number',
      'instructions' => 'Set logo height. All non-integers will be removed.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array (
      'key' => 'field_58fce94c2adb3',
      'label' => 'Width',
      'name' => 'logo_width',
      'type' => 'number',
      'instructions' => 'This property defines the width of the container around the logo. 320 is recommended. All non-integers will be removed.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array (
      'key' => 'field_58fce91d03590',
      'label' => 'Position',
      'name' => 'logo_position',
      'type' => 'select',
      'instructions' => '<a href="https://www.w3schools.com/cssref/pr_background-position.asp" target="_blank">How to use the position property</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'select' => 'select',
        'left top' => 'left top',
        'left center' => 'left center',
        'left bottom' => 'left bottom',
        'right top' => 'right top',
        'right center' => 'right center',
        'right bottom' => 'right bottom',
        'center top' => 'center top',
        'center center' => 'center center',
        'center bottom' => 'center bottom',
      ),
      'default_value' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'return_format' => 'value',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58fce91d035a5',
      'label' => 'Repeat',
      'name' => 'logo_repeat',
      'type' => 'select',
      'instructions' => '<a href="https://www.w3schools.com/cssref/pr_background-repeat.asp" target="_blank">How to use the repeat property</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'select' => 'select',
        'no-repeat' => 'no-repeat',
        'repeat' => 'repeat',
        'repeat-x' => 'repeat-x',
        'repeat-y' => 'repeat-y',
      ),
      'default_value' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'return_format' => 'value',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58fd37b9d14bb',
      'label' => 'Link',
      'name' => 'logo_link',
      'type' => 'text',
      'instructions' => 'The page to which your are taken when you click your logo.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'better-custom-login',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_58fcede4b3124',
  'title' => 'Form Wrapper',
  'fields' => array (
    array (
      'key' => 'field_58fcede4b8b92',
      'label' => 'Width',
      'name' => 'form_wrapper_width',
      'type' => 'number',
      'instructions' => 'Change the default width of the login form. All non-integers will be removed.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 320,
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'min' => '',
      'max' => '',
      'step' => '',
    ),
    array (
      'key' => 'field_58fd716adaebf',
      'label' => 'Background Color',
      'name' => 'form_wrapper_background_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
    ),
    array (
      'key' => 'field_58fcede4b7d36',
      'label' => 'Background Image',
      'name' => 'form_wrapper_background_image',
      'type' => 'image',
      'instructions' => 'Add a background image to the login form.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
    array (
      'key' => 'field_58fcede4b8c37',
      'label' => 'Background Position',
      'name' => 'form_wrapper_background_position',
      'type' => 'select',
      'instructions' => '<a href="https://www.w3schools.com/cssref/pr_background-position.asp" target="_blank">How to use the position property</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'select' => 'select',
        'left top' => 'left top',
        'left center' => 'left center',
        'left bottom' => 'left bottom',
        'right top' => 'right top',
        'right center' => 'right center',
        'right bottom' => 'right bottom',
        'center top' => 'center top',
        'center center' => 'center center',
        'center bottom' => 'center bottom',
      ),
      'default_value' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'return_format' => 'value',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58fcede4b8c78',
      'label' => 'Background Repeat',
      'name' => 'form_wrapper_background_repeat',
      'type' => 'select',
      'instructions' => '<a href="https://www.w3schools.com/cssref/pr_background-repeat.asp" target="_blank">How to use the repeat property</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'select' => 'select',
        'no-repeat' => 'no-repeat',
        'repeat' => 'repeat',
        'repeat-x' => 'repeat-x',
        'repeat-y' => 'repeat-y',
      ),
      'default_value' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'return_format' => 'value',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58fcede4b932d',
      'label' => 'Background Size',
      'name' => 'form_wrapper_background_size',
      'type' => 'select',
      'instructions' => '<a href="https://www.w3schools.com/cssref/css3_pr_background-size.asp" target="_blank">How to use the size property</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'select' => 'select',
        'auto' => 'auto',
        'cover' => 'cover',
        'contain' => 'contain',
        'flex' => 'flex',
      ),
      'default_value' => array (
        0 => 'none',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'return_format' => 'value',
      'placeholder' => '',
    ),
    array (
      'key' => 'field_58fcf0fae8203',
      'label' => 'Border Radius',
      'name' => 'form_wrapper_border_radius',
      'type' => 'text',
      'instructions' => 'Example: 5px',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '5px',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58fcf117e8204',
      'label' => 'Border Width',
      'name' => 'form_wrapper_border_width',
      'type' => 'text',
      'instructions' => 'Example: 1px',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '1px',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58fcf132e8205',
      'label' => 'Border Color',
      'name' => 'form_wrapper_border_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
    ),
    array (
      'key' => 'field_58fcf154e8206',
      'label' => 'Box Shadow',
      'name' => 'form_wrapper_box_shadow',
      'type' => 'text',
      'instructions' => 'Example: 0 1px 3px #999 (horizontal, vertical, spread, color).

<a href="https://www.w3schools.com/cssref/css3_pr_box-shadow.asp" target="_blank">How to use the box-shadow property</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0 1px 3px #999',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'better-custom-login',
      ),
    ),
  ),
  'menu_order' => 2,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_58fcf42440000',
  'title' => 'Form Fields',
  'fields' => array (
    array (
      'key' => 'field_58fcf4d0e5f50',
      'label' => 'Label Font Size',
      'name' => 'form_fields_label_font_size',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '14px',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58fcf4f5e5f51',
      'label' => 'Label Color',
      'name' => 'form_fields_label_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#777',
    ),
    array (
      'key' => 'field_58fd2928a0155',
      'label' => 'Input Background Color',
      'name' => 'form_fields_input_background_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#fbfbfb',
    ),
    array (
      'key' => 'field_58fd2a74536c9',
      'label' => 'Input Background Focus Color',
      'name' => 'form_fields_input_background_focus_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
    ),
    array (
      'key' => 'field_58fd2969a0156',
      'label' => 'Input Border Radius',
      'name' => 'form_fields_input_border_radius',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '5px',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58fd3357536ca',
      'label' => 'Input Border Color',
      'name' => 'form_fields_input_border_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#ddd',
    ),
    array (
      'key' => 'field_58fd33a764c51',
      'label' => 'Input Box Shadow',
      'name' => 'form_fields_input_box_shadow',
      'type' => 'text',
      'instructions' => 'Example: 0 1px 3px #999 (horizontal, vertical, spread, color).

<a href="https://www.w3schools.com/cssref/css3_pr_box-shadow.asp" target="_blank">How to use the box-shadow property</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '0 1px 3px #999',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58fd8030c8e94',
      'label' => 'Input Height',
      'name' => 'form_fields_input_height',
      'type' => 'text',
      'instructions' => 'Example: 40px (default: 28px)',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58fd8069c8e95',
      'label' => 'Input Padding',
      'name' => 'form_fields_input_padding',
      'type' => 'text',
      'instructions' => 'Example: 5px 10px',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58fd34cce24f2',
      'label' => 'Submit Button Color',
      'name' => 'form_fields_submit_button_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#fbfbfb',
    ),
    array (
      'key' => 'field_58fd34d8e24f3',
      'label' => 'Submit Button Hover Color',
      'name' => 'form_fields_submit_button_hover_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
    ),
    array (
      'key' => 'field_58fd34e0e24f4',
      'label' => 'Submit Button Border Color',
      'name' => 'form_fields_submit_button_border_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
    ),
    array (
      'key' => 'field_58fd3566e24f6',
      'label' => 'Submit Button Border Width',
      'name' => 'form_fields_submit_button_border_width',
      'type' => 'text',
      'instructions' => 'Example: 1px',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58fd7adf11965',
      'label' => 'Submit Button Box Shadow',
      'name' => 'form_fields_submit_button_box_shadow',
      'type' => 'text',
      'instructions' => 'Example: 0 1px 3px #999 (horizontal, vertical, spread, color).

<a href="https://www.w3schools.com/cssref/css3_pr_box-shadow.asp" target="_blank">How to use the box-shadow property</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58fd820bde7e2',
      'label' => 'Submit Button Height',
      'name' => 'form_fields_submit_button_height',
      'type' => 'text',
      'instructions' => 'Example: 40px (default: 28px)',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58fd7b1411966',
      'label' => 'Submit Button Text Shadow',
      'name' => 'form_fields_submit_button_text_shadow',
      'type' => 'text',
      'instructions' => 'Example: 0 1px 3px #999 (horizontal, vertical, radius, color).

<a href="https://www.w3schools.com/cssref/css3_pr_text-shadow.asp" target="_blank">How to use the box-shadow property</a>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58fd8234de7e3',
      'label' => 'Submit Button Font Size',
      'name' => 'form_fields_submit_button_font_size',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58fd7ff1c8e93',
      'label' => 'Make Submit Button Full-Width',
      'name' => 'form_fields_make_submit_button_full_width',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
      'ui' => 1,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'better-custom-login',
      ),
    ),
  ),
  'menu_order' => 3,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_58fd35e5a7759',
  'title' => 'Bottom Nav Links',
  'fields' => array (
    array (
      'key' => 'field_58fd36177101d',
      'label' => 'Bottom Nav Text Color',
      'name' => 'bottom_nav_links_bottom_nav_text_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#999',
    ),
    array (
      'key' => 'field_58fd36637101f',
      'label' => 'Bottom Nav Text Hover Color',
      'name' => 'bottom_nav_links_bottom_nav_text_hover_color',
      'type' => 'color_picker',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '#00a0d2',
    ),
    array (
      'key' => 'field_58fd372971020',
      'label' => 'Bottom Nav Position',
      'name' => 'bottom_nav_links_bottom_nav_position',
      'type' => 'select',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'left' => 'left',
        'right' => 'right',
        'center' => 'center',
      ),
      'default_value' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'return_format' => 'value',
      'placeholder' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'better-custom-login',
      ),
    ),
  ),
  'menu_order' => 4,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_58fd420ef1aff',
  'title' => 'Advanced',
  'fields' => array (
    array (
      'key' => 'field_58fd4234fb141',
      'label' => 'Custom CSS',
      'name' => 'advanced_custom_css',
      'type' => 'acf_code_field',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'mode' => 'css',
      'theme' => '3024-day',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'better-custom-login',
      ),
    ),
  ),
  'menu_order' => 5,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'left',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;